### ISSUE TITLE
Can't add new photographers

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#100]
Jay is trying to add additional photographers to the site. The admin template will not let him do this unless he fills out the template completely with information that they are not collecting (usage data/contacts/etc).

The last photographer he added was on July 13 and there were not problems…this was after the upgrade in June. Today, while the template is the same, it requires the additional data to exit.

**Comment by alecpm** [comment]
This should be fixed.

**Comment by skleinfeldt** [comment]
Jay confirms.
