### ISSUE TITLE
Estimate for displaying rare/endangered/etc. information

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#101]
Please provide an estimate for creating this new feature:

When the simple key is used and a result set is displayed, show how are threatened, endangered, or rare underneath the total number "## matching results".

**Comment by skleinfeldt** [comment]
@davisagli maybe you could take this one?

**Comment by davisagli** [comment]
Remember that status and rank can be set for various geographic areas (global, US & Canada, and per state). So what specific conditions should cause a species to be included in these counts? Should we also somehow visually indicate which species are included?

**Comment by skleinfeldt** [comment]
I had totally forgotten about that, now Dennis' request makes perfect sense. He had originally asked to show the rare/etc. numbers *when a user selects a state* on the simple key. I changed the request thinking "oh it would be easier to show it all the time instead of a special case." Wrong. Please estimate for showing the info only in the situation where a state is selected. (Or feel free to offer another idea.)

I'm leery about showing a visual indication of which species without getting the designer to weigh in, so let's leave that for now. (Good idea, maybe later.)

**Comment by davisagli** [comment]
Ah, got it. I think that can be done in a few hours.

**Comment by skleinfeldt** [comment]
Thank you! I have passed on this info.
