### ISSUE TITLE
TypeError at /dumpdata/

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#102]
From Jay:

I cannot export from the staging area to the production site.
There are 3 orchids that I have marked to deploy.

Hexalectris parviflora
Polystachya concreta
Triphora trianthophoros

I believe it may be the last one that is causing trouble. This orchid had been on the site earlier but I had to take it down due to a name change.

**Comment by davisagli** [comment]
I'm taking a look at this one, sorry didn't see that you assigned it to @alecpm

**Comment by davisagli** [comment]
I fixed an issue that probably happened when we merged changes from gobotany; seems to be working now.

**Comment by alecpm** [comment]
Thanks @davisagli!  I think I caught sight of this one when doing my migration stuff, but it's nice to not have to stop that work (which appears to be mostly done) in order to fix it for staging.

**Comment by skleinfeldt** [comment]
Fabulous teamwork. I'll ask Jay to test.

**Comment by skleinfeldt** [comment]
Jay confirms this is fixed.
