### ISSUE TITLE
Case sensitivity in search box

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#103]
From Jay:

On the Go Orchids home page/Find an orchid by location/the SEARCH feature, in Internet Explorer and Firefox:

- If I type in ‘f’, then click on ‘Florida’ in the drop down box option…all works well.
- If I type in ‘Florida’ it is MUCH slower to find the orchids in Florida.
- If I type in ‘florida’ it does not produce any results.

**Comment by davisagli** [comment]
I'm having trouble believing that the 2nd bullet is anything other than a coincidence, because the URL it goes to is the same as for the first bullet.

Confirmed bullet 3. We need to either capitalize the input before submitting the form or do a case insensitive query for the location character.

**Comment by skleinfeldt** [comment]
Whichever solution you think is best. Unless this will be surprisingly time consuming, feel free to proceed.

**Comment by skleinfeldt** [comment]
@alecpm is this one fixed?

**Comment by alecpm** [comment]
No this has not yet been addressed AFAIK.

**Comment by alecpm** [comment]
This is fixed now on staging and production.

**Comment by skleinfeldt** [comment]
I will ask Jay to confirm all these fixes. (This and #106, #107, #108, #109)

**Comment by skleinfeldt** [comment]
Jay confirms fix.
