### ISSUE TITLE
NoReverseMatch error

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#104]
Jay has identified a bug on the upgrade testing site. He created a new taxon and got this error when he tried to edit the species characters. The new taxon = Bletilla striata. He says the feature works on staging.
![9-23-15-error](https://cloud.githubusercontent.com/assets/1198463/10055652/672f2b40-6205-11e5-9b10-b808df80b476.jpg)

**Comment by skleinfeldt** [comment]
From Jay, I will tell him you are still working. (And I'll assign this to @alecpm unless I hear otherwise.)

"I am still seeing this bug on the dev site, i.e. I can’t edit the character values…is this something Alec is still working on? -Jay"

**Comment by alecpm** [comment]
Should be fixed now.

**Comment by skleinfeldt** [comment]
I think Jay confirms the fix (although didn't mention by name), close this when deployed to prod.

**Comment by skleinfeldt** [comment]
Assuming this is now live and I can close this ticket.
