### ISSUE TITLE
Get more questions not completely working

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#105]
This is related to the problem @alecpm  fixed on the production site last week but it is not fixed on the dev site. t relates to the Simple Key. The ‘get more questions’ feature is not completely working. Jay says "it’s like before so I’m sure Alec can quickly fix it." :)

**Comment by alecpm** [comment]
I merged the code to the migrated branch when I made the fix, but never pushed it (I tried but Heroku was misbehaving and then I forgot).  It's live now.

**Comment by skleinfeldt** [comment]
Asked Jay to verify.

**Comment by skleinfeldt** [comment]
Jay said this:

The ‘get more questions’ function is fixed now. Alec is aware of that annoying last choice, ‘place’ which is not active and to be honest, I have no idea what it could be, it appears on the public site as well as an inactive choice (Alec suggested he might be able to hide or delete it).

And then a day later he said this:

I have some more info on that ‘place’ box that does not seem to be turned on when you ask for more questions in the Simple Key…this is what should happen. On the Species page, when you ‘expand all characteristics’ and click the ‘place’ bar you get:

![jay-picture-of-place-in-simple-key-9-2015](https://cloud.githubusercontent.com/assets/1198463/10105865/1889f918-637f-11e5-80e2-1089b8226e19.jpg)

Should I close this ticket or does something else need to be done? Is it a new ticket?

**Comment by alecpm** [comment]
I've implemented a fix on dev.  It's ready to deploy to staging/production, I think.

**Comment by alecpm** [comment]
It's deployed everywhere now.

**Comment by skleinfeldt** [comment]
Jay approves.
