### ISSUE TITLE
Apparently Secure not recognized as a term on the Conservation Table

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#107]
From Jay:

From the beginning, there was an issue with the Conservation Table on the Species page. There are several choices including Secure and Apparently Secure. Both terms appear in the Glossary, and throughout the text on the site, the definition for each term is correctly displayed and its definition linked to the Glossary. However on the Conservation table, Apparently Secure is not recognized as a distinct term.

@alecpm says "glossary terms with overlapping terms is probably the root of this".

**Comment by alecpm** [comment]
This is fixed on staging and production (it was a case-sensitivity/capitalization issue).

**Comment by skleinfeldt** [comment]
Jay confirms fix.
