### ISSUE TITLE
Update photo citation information (notably Source)

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#108]
From Jay:

This is related to the earlier Go Botany upgrade - before that the information was correctly displayed. The citation for the expanded image does not include SOURCE; this information is correctly displayed on the species page when you mouse over an image in the carousel. Some contributors have specifically asked that this information, e.g. their website, be included…we need to correct this.

**Comment by alecpm** [comment]
This should be fixed on production and staging.

**Comment by skleinfeldt** [comment]
Jay says this is not quite right still. He says they do not have an ‘image reuse contact’, they do not collect this information. He says they would like the image citation information for the expanded images to read the same as when an image is moused-over in the carousel. (Without the "For reuse contact")

I spot checked several images and did not see this problem, except for the one image Jay found it on: go to http://goorchids.northamericanorchidcenter.org/species/bulbophyllum/pachyrachis/?pile=orchid-monocots and click on the 4th image from the left, for fruits. Could it be that this image has a space or some sort of ghost value in that field?

**Comment by alecpm** [comment]
The for reuse contact is coming from the GoBotany JS code and is automatically paired with the source field when it is present, we can customize it to remove that language on our branch.

**Comment by skleinfeldt** [comment]
Ah - yes please, make that customization, that automatic pairing is apparently not appropriate for Go Orchids.

**Comment by alecpm** [comment]
This is fixed

**Comment by skleinfeldt** [comment]
Jay confirms!
