### ISSUE TITLE
Un-limit image types shown in drop down

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#109]
From Jay:

On the Simple Key page, the default is to show FLOWER images…this is correct. Currently the drop down box only allows us to show photos of flowers, inflorescences and leaves. Initially we chose to limit the types of images displayed because we were missing so many. However it would be very helpful to add in all the image types now…this will allow side-by-side comparisons e.g. the three leafless epiphytes have very distinctive roots- displaying them in the Key would confirm identification.

**Comment by alecpm** [comment]
This should be fixed on staging and production.

**Comment by skleinfeldt** [comment]
Jay confirms fix.
