### ISSUE TITLE
Increase the size of the text string for the pollinator character

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#112]
It is currently 1000 chars. Waiting for Dennis/Jay to tell us the new max.

**Comment by skleinfeldt** [comment]
Dennis says "The largest block that I found has 1775 characters so my guess is that if we can have enough space for 2000 to 2500 characters we will not have any problems."

So maybe 3000 to be sure?

**Comment by alecpm** [comment]
This is completed and deployed to staging for data entry.  If no issues come up I'll deploy to production prior to the updated data being imported.

**Comment by alecpm** [comment]
I used 2500.

**Comment by skleinfeldt** [comment]
@alecpm I assume this is deployed and can be closed?

**Comment by alecpm** [comment]
Yes, the change is applied to production.
