### ISSUE TITLE
Change footer address

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#113]
On the Go Orchids web site we need to change the address slightly on the footer of each page. The address currently reads:

c/o Smithsonian Environmental Research Center
P.O. Box 28, 647 Contees Wharf Rd.
Edgewater, MD 21037
Contact: naocc@si.edu

We need to drop the PO Box 28. The address should be:

c/o Smithsonian Environmental Research Center
647 Contees Wharf Rd.
Edgewater, MD 21037
Contact: naocc@si.edu

**Comment by skleinfeldt** [comment]
Assigning to @davisagli to work on the week of 12/12/2016, along with #114.

**Comment by davisagli** [comment]
I took care of this.

**Comment by skleinfeldt** [comment]
Belated thanks @davisagli 

A question from Jay: Will the copyright date automatically change from 2016 to 2017 throughout the site (footer and images) next year?  If not, I'll make another ticket for that.

**Comment by davisagli** [comment]
It looks like it is set up to update automatically.
