### ISSUE TITLE
Apply Django 1.8 security fixes

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#115]
As pointed out on #97. @davisagli would this be doable with the other work you are doing the week of 12/12/2016? If it is bigger please tell us about how big.

**Comment by davisagli** [comment]
You have me scheduled for another project on 12/12 and I still have a maximum of 15 hours available for Jazkarta, so no, you can't just keep adding hours. That's how we get in situations where I can't use all the hours and we get behind.

I would guess this requires a few hours. The actual upgrade is simple, but we should review to see if anything will cause problems, and test things with it applied.

**Comment by skleinfeldt** [comment]
Thanks for the estimate @davisagli I'll run this by Jay and Dennis - it will probably use the rest of our contracted time.

I've adjusted your hours for 12/12, although I still haven't finished planning that week. I was only thinking of adding this ticket if it was trivial, but suspected that would not be the case.

**Comment by skleinfeldt** [comment]
@alecpm has this already been done?

**Comment by alecpm** [comment]
The site is on Django 1.8.3, the last 1.8 release was 1.8.19. It's probably a good idea to test an upgrade there. However, I don't think we should consider it until after we've completed the stack upgrade and spent some time running on the new stack so if anything comes up we have a better idea of the actual source of issues.

**Comment by skleinfeldt** [comment]
Sounds good.

**Comment by skleinfeldt** [comment]
Go Orchids upgraded to latest Go Botany and Django versions, moved to AWS and stack upgraded today.
