### ISSUE TITLE
Clean up training line feeds

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#116]
While testing #114 Jay noticed that the spacing between the sections was inconsistent - sometimes one line, sometimes 2 - and tracked it down to there sometimes being an extra blank line at the end of text in the Facts About. He can clean these up as he finds them, but he wanted to know if it was possible to write a script to do this throughout the site, and if so how much time would it take?

Assigning to @davisagli for an estimate (since you were in here most recently).

**Comment by davisagli** [comment]
It might make as much sense to make the template filter out trailing space rather than run a script to change the stored data. That should take under an hour.

**Comment by skleinfeldt** [comment]
Sounds good, title adjusted. Jay asks us to proceed with this - tentatively added to plan for next week @davisagli.

**Comment by davisagli** [comment]
Okay I did this for all the fields that are rendered with newlines preserved.

**Comment by skleinfeldt** [comment]
Thanks! I have asked Jay to test.

**Comment by skleinfeldt** [comment]
Jay says it looks good (although he also said he'd continue to test.) Closing.
