### ISSUE TITLE
Incomplete grid lines

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#117]
The grid system in the Simple Key appears incomplete at times. In the screenshot, notice that the grid lines are missing between Cyclopogon cranichoides and Cyclopogon elatus. 

![incomplete-grid-lines-screenshot](https://user-images.githubusercontent.com/1198463/46878276-dbf70e00-ce10-11e8-952f-e0b13f916d46.jpg)

**Comment by davisagli** [comment]
That was an intentional feature to visually group species from the same genus.

**Comment by skleinfeldt** [comment]
Thank you @davisagli - I had completely forgotten about that!

**Comment by skleinfeldt** [comment]
Thank you @davisagli - I had completely forgotten about that!
