### ISSUE TITLE
Django (and dependencies) Upgrade

### ISSUE THREAD

**Issue by alecpm** [jazkarta/goorchids-app#123]
Github is recommending we move to Django==1.11.29, and Go Botany is currently on Django==1.11.22. Go Orchids is currently only on 1.8.3. I suspect the upgrade from 1.11.29 to 1.11.22 won't be huge, the difficulties will be in getting us onto the latest GoBotany codebase which will facilitate moving from 1.8.3 to 1.11.22 and further. Looking through the GoBotany commit history, the Django upgrade itself looks pretty straightforward. Almost all of the Django upgrade related commits involve few changes beyond the version bump itself. It's not entirely clear what sorts of DB migrations will be needed during the upgrade process, but the development work seems likely to be relatively straightforward.

Though the Django upgrade seems straightforward, it's not clear that merging in the latest tagged GoBotany changes will be trivial. There are various changes large and small in the GoBotany codebase since we last synced it beyond the Django upgrades (Feb 5, 2016 was the last GoBotany commit that we have in our sub-repo). For example GoBotany has the moved away from Django Piston for the REST APIs, which could require some refactoring of custom GoOrchids API code (though GoOrchids does not use Django Piston directly, so that may not be an issue). There are potentially changes to specific views and methods that we in turn customize which will have to be accounted for if we want to pull in the latest GoBotany changes. If that weren't the case I think we could manage the Django upgrade in 3 - 4 hours of development and testing time, but because of the uncertainties around what may have changed in GoBotany and how that impacts our customizations, I'd be more comfortable estimating it at 6 - 12 hours.

It's likely we will need extensive testing of the backend and especially the front end by GoOrchids staff during this process, which may be a roadblock to getting it done expediently.

**Comment by skleinfeldt** [comment]
@alecpm Maybe we should separate the work of doing the Django upgrade from getting back in sync with Go Botany. It sounds like the former is pretty easy and the latter involves quite a bit of work. And as noted on #129 we should probably do the Django upgrade soon for security reasons.

**Comment by alecpm** [comment]
@skleinfeldt I think you misunderstood. We probably can't move from 1.8.3 to 1.11.22 without first resyncing with Go Botany and fixing whatever incompatibilities may arise. We can try, but it would likely mean duplicating work that was already done on Go Botany. The upgrade from 1.11.22 to 1.11.29 should be easy for Go Botany, but Go Orchids is still way behind.

**Comment by skleinfeldt** [comment]
Oh sorry for the misunderstanding, now I get it. So this will just take a chunk of time, no way around it.

**Comment by skleinfeldt** [comment]
When we do this work we should consider disabling dependabot on Go Orchids. (That was in my notes from somewhere.)

**Comment by skleinfeldt** [comment]
Go Orchids upgraded to latest Go Botany and Django versions, moved to AWS and stack upgraded today.
