### ISSUE TITLE
Develop a database migration script

### ISSUE THREAD

**Issue by chiruzzimarco** [jazkarta/goorchids-app#139]
Develop a database migration script. Figure out a solution for `gobotany` [custom migrations](https://github.com/jazkarta/gobotany-app/tree/4967b16c265f3299a711cfae43d420ee1b0d8744/gobotany/core/migrations)

**Comment by skleinfeldt** [comment]
Go Orchids upgraded to latest Go Botany and Django versions, moved to AWS and stack upgraded today.
