### ISSUE TITLE
Adjust Heroku maintenance window

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#142]
Make it a few hours earlier so it isn't so noticeable for the Eastern TZ. 4:00 AM eastern on Sunday might be good.

**Comment by chiruzzimarco** [comment]
Unfortunately this feature is available only on standard, premium, private and shield plans.

Quoting @alecpm :

> we probably just have to live with the preset maintenance window. The app doesn’t need to be high availability and this is a rare occurrence that fixed itself as expected.

@skleinfeldt Feel free to re-open if this is not satisfactory.
