### ISSUE TITLE
Remove/replace Redis-To-Go add-on by August 8, 2022

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#143]
Per the attached Heroku notice.
[Shutdown Notice Redis-To-Go Heroku add-on.pdf](https://github.com/jazkarta/goorchids-app/files/9048666/Shutdown.Notice.Redis-To-Go.Heroku.add-on.pdf)

**Comment by chiruzzimarco** [comment]
The Redis-To-Go Heroku plugin was removed and replaced by the Heroku Redis plugin.
