### ISSUE TITLE
Homepage changes

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#95]
Per Jay's mockup:

  - Add a link to the NAOCC site in the nav bar
  - Change existing link to NAOCC to a link to the video
  - Share ‘Orchid of the Day’ real estate with the embedded Go Orchids video

**Comment by davisagli** [comment]
Ready for review on http://goorchids-staging.herokuapp.com

**Comment by skleinfeldt** [comment]
Looks awesome! I'll email Jay to make sure he sees this.

**Comment by skleinfeldt** [comment]
Jay is happy, is having Dennis review. But Jay says "the Go to Video Tutorial bar does not seem to work."

**Comment by skleinfeldt** [comment]
Update: Dennis is ok with the Homepage "once we get the tab working" and Jay updates the text. (I think he is working on that.)

**Comment by skleinfeldt** [comment]
From David: the "go to video" button was not working in Firefox and is now fixed.
