### ISSUE TITLE
Glossary issue

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#96]
Jay is having trouble creating a glossary term that uses a photo instead of a dumb little drawing. Details:

Orchid species = Platanthera leucophaea
Glossary term = Sphinx eremitus
Glossary definition =photo ©Ron Panzer
Image = sphinx-eremitus-rpanzer-sm.gif (I am using naming convention similar to other images in the Glossary).

Our Goal: We are collecting images of known insect pollinators that we would like to display on Go Orchids with the associated orchid. Because one insect species may pollinate several orchids, and a single orchid may have several pollinators, and more importantly, we want the name of the insect to appear with the image, I have decided to use the Glossary, and not an orchid’s Species Page (carousel on top), to display the insect image.

What I did:
  - On the admin site in the staging area, I have gone to Platanthera leucophaea Species Page and in the text box for Pollination, I entered ‘Sphinx eremitus’.
  - Next I entered the Glossary Term ‘Sphinx eremitus’ onto the admin page in the staging area.
  - I then entered the Lay Definition associated with this word: ‘photo ©Ron Panzer’ (credit to the photographer)
  - Finally, I uploaded the image: sphinx-eremitus-rpanzer-sm.gif from the admin site…I did not do a bulk upload but browsed directly from the admin site.

What I am hoping to see:

  - The Glossary term ‘Sphinx eremitus’ should appear in the Glossary (it appears on the admin page, but not in the Glossary in the staging area)
  - When I go to the Platanthera leucophaea page, expand All Characteristics, then expand Facts and Uses I see that in the Pollination box ‘Sphinx eremitus’ is highlighted but when I mouse over the words only the text ‘photo ©Ron Panzer’ appears there is no image!
  - The image does appear in the S3 browser

What happens:

  - On the first screen of the S3 browser, there is a new file that was created.
  - The file name is ls-taxon-images.gz. I cannot open this file, but it seems to be related to the image that I uploaded into the Glossary. This file is modified, based on the date, each time I’ve uploaded the Sphinx eremitus image.

**Comment by skleinfeldt** [comment]
Alec's analysis:

Glossary terms that start with capitalized letters are not displayed in the glossary (though they will still highlight and show definition on species pages, etc.).  This may be a bug or it may be intentional behavior (I'm looking into the code that renders the list).  Similarly, the case of the image must match the case of the term, so either the term should be changed to "sphinx eremitus" or the image filename changed to "Sphinx-eremitus-rpanzer-sm.gif" to ensure the image appears.

**Comment by alecpm** [comment]
I've got a fix in place: jazkarta/gobotany-app@d545d52fbd5940b90dcf794060f607239813e1e5

**Comment by skleinfeldt** [comment]
Great, can you deploy to staging so they can test?

**Comment by alecpm** [comment]
Deployed and working:

http://goorchids-staging.herokuapp.com/species/platanthera/leucophaea/

**Comment by skleinfeldt** [comment]
Nice. (it's under Facts and Uses.) Sent to Jay for testing.

**Comment by skleinfeldt** [comment]
Jay says: "This is exactly what I was hoping for...thanks to Alec...you guys came thru fast on these issues."
