### ISSUE TITLE
Django upgrade

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#97]

**Comment by skleinfeldt** [comment]
@davisagli want to take this one next?

**Comment by skleinfeldt** [comment]
Go Botany has finished their upgrade work, and we have finished our Go Botany code merge work, so we are good to go. We'll be scheduling a sprint to do this in September.

**Comment by skleinfeldt** [comment]
Jay has tested and approved the upgrade, we are good to deploy to production.

**Comment by skleinfeldt** [comment]
Assuming this is now live and I can close this ticket.

**Comment by alecpm** [comment]
This is not yet live, except on Dev.

**Comment by skleinfeldt** [comment]
Oh! Sorry my bad memory - what are we waiting for to deploy to prod?

**Comment by skleinfeldt** [comment]
@alecpm when #108 is done should I ask Jay for permission to deploy the upgrade to prod?

**Comment by alecpm** [comment]
Yeah, once we have all fixes in place and he's comforter that he's tested
all features on the second server, I can upgrade staging and then
production.

**Comment by skleinfeldt** [comment]
Scheduled for evening of 1/12/2016.

**Comment by skleinfeldt** [comment]
@alecpm can we close this now? :-)

**Comment by davisagli** [comment]
The upgrade to Django 1.8 is complete, as far as I know. But there are a number of security releases for Django 1.8 that we haven't installed.

Note that Django support for 1.8 ends in April 2018.

**Comment by skleinfeldt** [comment]
Thanks @davisagli made a ticket for that. I'll close this.
