### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/goorchids-app#99]
From Jay:

With the upgrade [incorporating latest Go Botany code], something that is now different relates to the citation of the images...there is now the addition of 'for reuse: contact' This is information we are not collecting and should be removed from the display. This did not appear earlier in the testing and I was specifically looking for it since this feature is now on Go Botany. The problem does not occur when images are moused over in the carousel, the ‘for reuse:contact’ phrase only appears in the expanded image citation. (This seems to be a Go Botany innovation that slipped in with the recent upgrade. We are not collecting this information and this dead link needs to be removed.)

There is also an issue with images that appear on the Genus and Orchid Family pages…although it doesn’t appear as expandable…these images can be expanded when clicked on. That is, the images don't signal (with the pointing finger) that they can be expanded...however, if you click on them...they expand.

**Comment by skleinfeldt** [comment]
@alecpm can you fix these issues sometime this week? They are not super high priority but we don't want to forget.

**Comment by alecpm** [comment]
This week might be tight, but I'll try for next.

**Comment by skleinfeldt** [comment]
You are sooo right, this week has gotten too jammed; next week is fine.

**Comment by alecpm** [comment]
These issues should be fixed now.  You may need to shift reload to clear your cache though.

**Comment by skleinfeldt** [comment]
Jay confirms - thanks!
